services:
  mongo:
    image: mongo:7.0.16
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - mongo:/hamptons-home-management/data/db
    logging:
      driver: none
volumes:
  mongo:
